arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: l10n-error.txt
output-dir: lib/gen/
preferred-supported-locales:
  - en

# Enable translation (via DeepL)
translate: true
# Auto-run flutter gen-l10n after extraction
generate: true
# Key prefix for translations
key-prefix: AppLocalizations.of(context).
# Generate key name
# "ask" = prompt with pre-filled text, true = infer from text, false = prompt manually
auto-name-key: true
# Language to use for key name generation
key-name-language: en
# Import line to insert if needed
import-line: import 'package:fast_driver_app/l10n/gen/app_localizations.dart';
# Explicitly set source language code for translation fallback
source-language: ""
